name: Test and Deploy

on:
  push:
    branches:
      - dev
      - prod

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build -t test-image .

  deploy_dev:
    if: github.ref == 'refs/heads/dev'
    needs: test-build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: checkout_dev
        name: Checkout code
        uses: actions/checkout@v4

      - id: auth_dev
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: 'mv-dev-388916'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: deploy_dev
        name: Deploy to beta service
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'mv-frontend-beta'
          region: 'us-central1'
          source: '.'

  deploy_prod:
    if: github.ref == 'refs/heads/prod'
    needs: test-build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: checkout_prod
        name: Checkout code
        uses: actions/checkout@v2

      - id: auth_prod
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: deploy_prod
        name: Deploy to production service
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'mv-frontend'
          region: 'us-central1'
          source: "."
